### ISSUE TITLE
JSON::ParserError: 776

### ISSUE THREAD

**Issue by lgs** [DigixGlobal/ethereum-ruby#7]
Binding Ethereum node into a Rails app, get 'JSON::ParserError: 776'.
I have a node running APIs via IPC like:

<pre>geth --ipcapi "admin,eth,debug,miner,net,shh,txpool,personal,web3"</pre>

and in Rails console I can do

<pre>client = Ethereum::IpcClient.new("#{ENV['HOME']}/.ethereum/geth.ipc")</pre>

but when I try `puts client.coinbase["result"]` I get and error:

<pre>JSON::ParserError: 776: unexpected token at '{"jsonrpc":"2.0","error":{"code":-32600,"message":"EOF"}}</pre>

**Comment by lgs** [comment]
oh my gosh ...

<pre>
lsoave@basenode:~/github/ethereum-ruby$ bundle exec rspec
Ethereum
  HttpClient
    should work
  IpcClient
    should work (FAILED - 1)
    should support batching (FAILED - 2)
Ethereum
  Ethereum Version
    has a version number (FAILED - 3)
  Deployment
    should deploy a contract with parameters (FAILED - 4)
  Basic contract testing
    should perform a contract transaction, wait for its completion, return an Ethereum::Transaction object (FAILED - 5)
    should test a call_(Ethereum Contract Function) (FAILED - 6)
Failures:
  1) Ethereum IpcClient should work
     Failure/Error: socket = UNIXSocket.new(@ipcpath)
     
     Errno::ENOENT:
       No such file or directory - connect(2) for /home/lsoave/EtherDev/data/geth.ipc
     # ./lib/ethereum/ipc_client.rb:12:in `initialize'
     # ./lib/ethereum/ipc_client.rb:12:in `new'
     # ./lib/ethereum/ipc_client.rb:12:in `send_single'
     # ./lib/ethereum/client.rb:57:in `block (2 levels) in <class:Client>'
     # ./spec/client_spec.rb:17:in `block (3 levels) in <top (required)>'
  2) Ethereum IpcClient should support batching
     Failure/Error: socket = UNIXSocket.new(@ipcpath)
     
     Errno::ENOENT:
       No such file or directory - connect(2) for /home/lsoave/EtherDev/data/geth.ipc
     # ./lib/ethereum/ipc_client.rb:12:in `initialize'
     # ./lib/ethereum/ipc_client.rb:12:in `new'
     # ./lib/ethereum/ipc_client.rb:12:in `send_single'
     # ./lib/ethereum/ipc_client.rb:27:in `send_batch'
     # ./lib/ethereum/client.rb:24:in `batch'
     # ./spec/client_spec.rb:21:in `block (3 levels) in <top (required)>'
  3) Ethereum Ethereum Version has a version number
     Failure/Error: expect(Ethereum::VERSION).to eq("0.4.90")
     
       expected: "0.4.90"
            got: "1.5.2"
     
       (compared using ==)
     # ./spec/ethereum_spec.rb:12:in `block (3 levels) in <top (required)>'
  4) Ethereum Deployment should deploy a contract with parameters
     Failure/Error: sol_output = @client.compile_solidity(@file)
     
     NoMethodError:
       undefined method `compile_solidity' for #<Ethereum::HttpClient:0x0055b378496fc0>
     # ./lib/ethereum/initializer.rb:9:in `initialize'
     # ./spec/ethereum_spec.rb:18:in `new'
     # ./spec/ethereum_spec.rb:18:in `block (3 levels) in <top (required)>'
  5) Ethereum Basic contract testing should perform a contract transaction, wait for its completion, return an Ethereum::Transaction object
     Failure/Error: sol_output = @client.compile_solidity(@file)
     
     NoMethodError:
       undefined method `compile_solidity' for #<Ethereum::HttpClient:0x0055b378496fc0>
     # ./lib/ethereum/initializer.rb:9:in `initialize'
     # ./spec/ethereum_spec.rb:33:in `new'
     # ./spec/ethereum_spec.rb:33:in `block (3 levels) in <top (required)>'
  6) Ethereum Basic contract testing should test a call_(Ethereum Contract Function)
     Failure/Error: sol_output = @client.compile_solidity(@file)
     
     NoMethodError:
       undefined method `compile_solidity' for #<Ethereum::HttpClient:0x0055b378496fc0>
     # ./lib/ethereum/initializer.rb:9:in `initialize'
     # ./spec/ethereum_spec.rb:33:in `new'
     # ./spec/ethereum_spec.rb:33:in `block (3 levels) in <top (required)>'
Finished in 0.01874 seconds (files took 0.38199 seconds to load)
7 examples, 6 failures
Failed examples:
rspec ./spec/client_spec.rb:16 # Ethereum IpcClient should work
rspec ./spec/client_spec.rb:20 # Ethereum IpcClient should support batching
rspec ./spec/ethereum_spec.rb:11 # Ethereum Ethereum Version has a version number
rspec ./spec/ethereum_spec.rb:17 # Ethereum Deployment should deploy a contract with parameters
rspec ./spec/ethereum_spec.rb:39 # Ethereum Basic contract testing should perform a contract transaction, wait for its completion, return an Ethereum::Transaction object
rspec ./spec/ethereum_spec.rb:44 # Ethereum Basic contract testing should test a call_(Ethereum Contract Function)
</pre>

**Comment by alexhanh** [comment]
@lgs what version of geth are you running? I got it working with my fork https://github.com/alexhanh/ethereum-ruby
`$ geth version
Geth
Version: 1.4.9-stable-b7e3dfc5`
`geth --datadir ~/EtherDev/data --minerthreads 1 --nodiscover --maxpeers 0 console`
`IPC endpoint opened: /Users/alexhanh/EtherDev/data/geth.ipc`

Then

```
client = Ethereum::IpcClient.new("/Users/alexhanh/EtherDev/data/geth.ipc")
puts client.eth_gas_price
{"jsonrpc"=>"2.0", "id"=>1, "result"=>"0x4a817c800"}
```

**Comment by lgs** [comment]
@alexhanh

<pre>
lsoave@basenode:~$ geth version 
Geth
Version: 1.4.9-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=/home/lsoave/go
GOROOT=/usr/lib/go
</pre>

<pre>
lsoave@basenode:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
lsoave@basenode:~$ uname -a
Linux basenode 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
</pre>

**Comment by lgs** [comment]
... ops,  i didn't realize you had used your own fork ...

**Comment by alexhanh** [comment]
I decided to release a simple JSON RPC client gem https://github.com/alexhanh/jeth. Perhaps ethereum-ruby could use that.

**Comment by lgs** [comment]
@alexhanh that's good idea but just use #new instead of #create: 

<pre>
$ rails c
Running via Spring preloader in process 5827
Loading development environment (Rails 5.0.0)
irb(main):001:0> client = Jeth::IpcClient.create
NoMethodError: undefined method `create' for Jeth::IpcClient:Class
    from (irb):1
...
irb(main):002:0> client = Jeth::HttpClient.create('http://localhost:8545')
NoMethodError: undefined method `create' for Jeth::HttpClient:Class
    from (irb):4
</pre>

<pre>
irb(main):057:0>  client = Jeth::HttpClient.new('http://localhost:8545')
=> # < Jeth::HttpClient:0x005621b980e6f8 @id=0,  @batch=nil, @host="localhost", 
     @port=8545, @ssl=false, @uri=#<URI::HTTP http://localhost:8545 > >
irb(main):058:0> client.eth_gas_price
=> {"jsonrpc"=>"2.0", "id"=>1, "result"=>"0x4a817c800"}
</pre>

<pre>
irb(main):059:0> client = Jeth::IpcClient.create
NoMethodError: undefined method `create' for Jeth::IpcClient:Class
    from (irb):59
irb(main):060:0> client = Jeth::IpcClient.new
=> #<Jeth::IpcClient:0x005621b973d288 @id=0, @batch=nil, @ipcpath="/home/lsoave/.ethereum/geth.ipc">
irb(main):061:0> client.eth_gas_price
=> {"jsonrpc"=>"2.0", "id"=>1, "result"=>"0x4a817c800"}
</pre>

the only one working like the README is `client = Jeth.create`

<pre>
irb(main):062:0> client = Jeth.create
=> #<Jeth::IpcClient:0x005621b96f07f8 @id=0, @batch=nil, @ipcpath="/home/lsoave/.ethereum/geth.ipc">
irb(main):063:0> client.eth_gas_price
=> {"jsonrpc"=>"2.0", "id"=>1, "result"=>"0x4a817c800"}
</pre>

**Comment by alexhanh** [comment]
@tymat This pull request fixes the issues https://github.com/DigixGlobal/ethereum-ruby/pull/8, feel free to close the issue.
